# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.hostname = "midserver"

  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=777"]

  config.vm.provision "shell", path: "build-dbserver-vm.sh"

   # VirtualBox provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024   # allocate 1 GB RAM (increase if needed)
    vb.cpus = 2        # give it 2 CPU cores
  end

end
