# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=777"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024   # allocate 1 GB RAM (increase if needed)
    vb.cpus = 2        # give it 2 CPU cores
  end

  config.vm.provision "shell", path: "build-frontend-vm.sh"
end
